version: '3.1'
#https://github.com/docker-library/postgres/issues/151
services:

  ldap:
    container_name: pacsldap
    image: dcm4che/slapd-dcm4chee:${PACS_LDAP_IMAGE_TAG}
    env_file: docker-compose.env
    volumes:
      - dcm4chee-ldap-ldap:/var/lib/openldap/openldap-data
      - dcm4chee-ldap-slapdd:/etc/openldap/slapd.d
    restart: on-failure
    networks:
      - pacs_network


  arcdb:
    container_name: arcdb
    image: dcm4che/postgres-dcm4chee:${PACS_DB_IMAGE_TAG}
    env_file: docker-compose.env
    volumes:
      - dcm4chee-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - pacs_network

  arc:
    container_name: pacsarc
    image: dcm4che/dcm4chee-arc-psql:${PACS_ARC_IMAGE_TAG}
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /storage /opt/wildfly/standalone
      WILDFLY_WAIT_FOR: ldap:389 arcdb:5432
#      JAVA_OPTS: -Djava.net.preferIPv4Stack=true
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8089,server=y,suspend=n
      POSTGRES_HOST: arcdb
#    mem_limit: 1024000
    depends_on:
      - ldap
      - arcdb
    volumes:
      - dcm4chee-arc-wildfly:/opt/wildfly/standalone
      - /dcm4chee-arc/storage:/storage
    restart: on-failure
    networks:
      - pacs_network

  auth-db:
    container_name: authdb
    image: postgres:${KHEOPS_AUTHORIZATION_PSQL_DATABASE_IMAGE_TAG}
    volumes:
      - kheops-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kheops
      - POSTGRES_USER=kheopsuser
      - POSTGRES_PASSWORD_FILE=/run/secrets/kheops_authdb_pass
    secrets:
      - kheops_authdb_pass
    restart: on-failure

  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:${KHEOPS_AUTHORIZATION_IMAGE_TAG}
    volumes:
      - logs_auth:/usr/local/tomcat/logs
    restart: on-failure
    env_file: docker-compose.env
    environment:
      - CATALINA_OPTS="-Duser.timezone=UTC"
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8089"
    ports:
      - "8089:8089"
    depends_on:
      - auth-db
      - arc
    secrets:
      - kheops_superuser_hmasecret
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_keycloak_clientsecret
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
      - kheops_metric_ressource_password
    extra_hosts:
      - "keycloak.kheops.online:10.5.5.29"
      - "reportprovider.kheops.online:10.5.5.33"
    networks:
      - kheops_network

  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:${KHEOPS_ZIPPER_IMAGE_TAG}
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - arc
    secrets:
      - kheops_client_zippersecret
    networks:
      - kheops_network

  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:${KHEOPS_UI_IMAGE_TAG}
    env_file: docker-compose.env
    restart: on-failure
    depends_on:
      - kheops-authorization
      - arc
    networks:
      - frontend_network

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:${KHEOPS_DICOMWEB_PROXY_IMAGE_TAG}
    restart: on-failure
    environment:
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8088"
    ports:
      - "8088:8088"
    env_file: docker-compose.env
    depends_on:
      - kheops-authorization
      - arc
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret
    volumes:
      - logs_proxy:/usr/local/tomcat/logs
    networks:
      - kheops_network

  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:${KHEOPS_REVERSE_PROXY_IMAGE_TAG}
    container_name: kheopsreverseproxy
    secrets:
      - privkey1.pem
      - fullchain1.pem
    env_file: docker-compose.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - arc
      - pacs-authorization-proxy
    extra_hosts:
      - "${ROOT_URL}:127.0.0.1"
      - "kibana.kheops.online:10.5.5.31"
    networks:
      - kheops_network
      - frontend_network

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    image: osirixfoundation/pacs-authorization-proxy:${PACS_AUTHORIZATION_PROXY_IMAGE_TAG}
    env_file: docker-compose.env
    depends_on:
      - arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post
    extra_hosts:
      - "kibana.kheops.online:10.5.5.31"
    networks:
      - pacs_network
      - kheops_network


secrets:
  kheops_authdb_pass:
    file: ${SECRETS_PATH}/kheops_authdb_pass
  kheops_pacsdb_pass:
    file: ${SECRETS_PATH}/kheops_pacsdb_pass
  kheops_superuser_hmasecret:
    file: ${SECRETS_PATH}/kheops_superuser_hmasecret
  kheops_auth_hmasecret:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret_post
  privkey1.pem:
    file: ${NGINX_KEY}/privkey1.pem
  fullchain1.pem:
    file: ${NGINX_KEY}/fullchain1.pem
  kheops_keycloak_clientsecret:
    file: ${SECRETS_PATH}/kheops_keycloak_clientsecret
  kheops_client_dicomwebproxysecret:
    file: ${SECRETS_PATH}/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: ${SECRETS_PATH}/kheops_client_zippersecret
  welcomebot_token:
    file: ${SECRETS_PATH}/welcomebot_token
  kheops_metric_ressource_password:
    file: ${SECRETS_PATH}/kheops_metric_ressource_password

volumes:
  dcm4chee-ldap-ldap:
  dcm4chee-ldap-slapdd:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  kheops-db-data:
  logs_auth:
  logs_proxy:
  
networks:
  kheops_network:
    driver: bridge
  pacs_network:
    driver: bridge
  frontend_network:
    driver: bridge
